yaml
name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Use Node JS
      uses: actions/setup-node@v1
      with:
        node-version: '18.x'
    - name: Install Packages
      run: npm install
    - name: Run Tests
      run: npm run test
